# Generated by Django 3.0.2 on 2020-03-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر',
            },
        ),
        migrations.CreateModel(
            name='Event_organizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=50, verbose_name='برگزارکننده')),
            ],
            options={
                'verbose_name': 'برگزارکننده',
                'verbose_name_plural': 'برگزارکننده',
            },
        ),
        migrations.CreateModel(
            name='Event_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'نوع',
                'verbose_name_plural': 'نوع',
            },
        ),
        migrations.CreateModel(
            name='Event_venues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100, verbose_name='نام محل')),
                ('venue_address', models.TextField(verbose_name='آدرس')),
                ('venue_map_lat', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='عرض جغرافیایی')),
                ('venue_map_long', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='طول جغرافیایی')),
                ('venue_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Cities', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'محل برگزاری',
                'verbose_name_plural': 'محل برگزاری',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('event_organizer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Event_organizers')),
                ('event_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Event_types')),
                ('event_venue', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Event_venues')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد',
            },
        ),
    ]
