# Generated by Django 3.0.2 on 2020-03-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(default='', verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(verbose_name='تاریخ و ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Event_organizers', verbose_name='برگزارکننده'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(verbose_name='تاریخ و ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Event_types', verbose_name='نوع رویداد'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Event_venues', verbose_name='محل برگزاری'),
        ),
    ]
