# Generated by Django 3.0.2 on 2020-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0003_event_event_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('guest_website', models.CharField(max_length=50, verbose_name='وبسایت')),
                ('guest_instagram', models.CharField(max_length=50, verbose_name='اینستاگرام')),
                ('guest_image', models.ImageField(blank=True, null=True, upload_to='profiles/avatar/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'مهمان',
                'verbose_name_plural': 'مهمان',
            },
        ),
    ]
