# Generated by Django 3.0.2 on 2020-03-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0006_event_guests_event_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Guests',
        ),
    ]
