# Generated by Django 3.0.2 on 2020-03-18 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0007_delete_event_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_guests', models.ManyToManyField(to='eventinfo.Guest')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Event')),
            ],
        ),
    ]
