# Generated by Django 3.0.2 on 2020-03-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0008_event_guests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Guests',
        ),
    ]
