# Generated by Django 3.0.2 on 2020-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0009_delete_event_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_guests',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='eventinfo.Guest'),
        ),
    ]
