# Generated by Django 3.0.2 on 2020-03-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0010_event_event_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='guest_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_image/profiles/avatar/', verbose_name='تصویر'),
        ),
    ]
