# Generated by Django 3.0.2 on 2020-03-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0011_auto_20200319_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_venues',
            name='venue_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main_image/venues/logo/', verbose_name='تصویر'),
        ),
    ]
