# Generated by Django 3.0.2 on 2020-03-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0012_event_venues_venue_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_venues',
            name='venue_logo',
        ),
        migrations.AddField(
            model_name='event_organizers',
            name='organizer_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main_image/organizers/logo/', verbose_name='تصویر'),
        ),
    ]
