# Generated by Django 3.0.2 on 2020-03-21 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventinfo', '0014_event_organizers_organizer_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_guests',
            field=models.ManyToManyField(blank=True, default=None, to='eventinfo.Guest'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('gender', models.IntegerField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], null=True, verbose_name='جنسیت')),
                ('bday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='main_image/users/avatar/', verbose_name='')),
                ('balance', models.IntegerField(default=0, verbose_name='اعتبار')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'پروفایل کاربری',
                'verbose_name_plural': 'پروفایل کاربری',
            },
        ),
    ]
