# Generated by Django 3.0.2 on 2020-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0015_auto_20200321_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'مرد'), (0, 'زن')], null=True, verbose_name='جنسیت'),
        ),
    ]
