# Generated by Django 3.0.2 on 2020-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0019_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_is_canceled',
            field=models.BooleanField(default=False, verbose_name='بلیت لغو شده'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت بلیت'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_type',
            field=models.IntegerField(choices=[(0, 'رایگان'), (1, 'پولی'), (2, 'حمایتی')], verbose_name='نوع بلیت'),
        ),
    ]
