# Generated by Django 3.0.2 on 2020-03-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0020_auto_20200322_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_types',
            name='type_icon',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='آیکن'),
        ),
    ]
