# Generated by Django 3.0.2 on 2020-03-27 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventinfo', '0022_auto_20200326_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_seats', models.IntegerField(verbose_name='تعداد')),
                ('book_created_at', models.DateTimeField(auto_now_add=True)),
                ('book_total_cost', models.IntegerField(verbose_name='قیمت کل')),
                ('book_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventinfo.Event', verbose_name='رویداد')),
                ('book_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventinfo.Tickets', verbose_name='بلیت')),
                ('book_time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventinfo.Time_Slots', verbose_name='سانس')),
                ('book_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزرو',
            },
        ),
    ]
