# Generated by Django 3.0.2 on 2020-03-28 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventinfo', '0023_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_event',
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticket_status',
            field=models.IntegerField(choices=[(1, 'بلیت فروشی آغاز نشده.'), (2, 'بلیت فروشی آغاز شده.'), (3, 'بلیت\u200cها تمام شد.'), (4, 'بلیت فروشی بسته شد.'), (5, 'رویداد به پایان رسیده'), (6, 'بلیت لغو شده'), (7, 'بلیت حذف شده')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Tickets', verbose_name='بلیت'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Time_Slots', verbose_name='سانس'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventinfo.Time_Slots', verbose_name='سانس'),
        ),
    ]
