# Generated by Django 3.0.2 on 2020-03-29 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0024_auto_20200329_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_order_start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='ساعت شروع فروش بلیت'),
        ),
    ]
