# Generated by Django 3.0.2 on 2020-03-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0026_auto_20200329_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_slots',
            name='time_slot_status',
            field=models.IntegerField(blank=True, choices=[(1, 'بلیت فروشی آغاز نشده.'), (2, 'بلیت فروشی آغاز شده.'), (3, 'بلیت\u200cها تمام شد.'), (4, 'بلیت فروشی بسته شد.'), (5, 'سانس به پایان رسیده'), (6, 'بلیت لغو شده'), (7, 'بلیت حذف شده')], null=True),
        ),
    ]
