# Generated by Django 3.0.2 on 2020-03-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0027_time_slots_time_slot_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='ticket_count',
            new_name='ticket_seats',
        ),
        migrations.AddField(
            model_name='time_slots',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
