# Generated by Django 3.0.2 on 2020-03-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0028_auto_20200330_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_slots',
            name='free_seats',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
