# Generated by Django 3.0.2 on 2020-04-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0029_time_slots_free_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_time_slot',
        ),
    ]
