# Generated by Django 3.0.2 on 2020-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0032_order_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
