# Generated by Django 3.0.2 on 2020-04-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0037_auto_20200405_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventinfo.Event', verbose_name='رویداد'),
            preserve_default=False,
        ),
    ]
