# Generated by Django 3.0.2 on 2020-04-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0038_order_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت پایان'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت شروع'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='بیشترین قیمت'),
        ),
        migrations.AddField(
            model_name='event',
            name='min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='شروع قیمت'),
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
