# Generated by Django 3.0.2 on 2020-04-09 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventinfo', '0039_auto_20200408_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
