# Generated by Django 3.0.2 on 2020-04-09 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventinfo', '0040_event_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
