# Generated by Django 3.0.2 on 2020-04-10 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventinfo', '0041_auto_20200410_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventinfo.Event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eventinfo_event_bookmarks',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', through='eventinfo.EventBookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
