# Generated by Django 3.0.2 on 2020-04-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0045_auto_20200410_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='موبایل'),
        ),
    ]
