# Generated by Django 3.0.2 on 2020-04-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0046_auto_20200411_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='رویداد آنلاین'),
        ),
        migrations.CreateModel(
            name='Digital_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.IntegerField(choices=[(1, 'وبینار'), (2, 'پخش زنده'), (3, 'فایل'), (4, 'ویدیو')], verbose_name='نوع لینک')),
                ('link_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان لینک')),
                ('link', models.URLField(max_length=300, verbose_name='آدرس')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventinfo.Event', verbose_name='رویداد')),
            ],
            options={
                'verbose_name': 'لینک\u200cهای دیجیتال',
                'verbose_name_plural': 'لینک\u200cهای دیجیتال',
            },
        ),
    ]
