# Generated by Django 3.0.2 on 2020-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0047_auto_20200416_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_firstname',
            field=models.CharField(default=1, max_length=50, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_lastname',
            field=models.CharField(default=None, max_length=50, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وبسایت'),
        ),
    ]
