# Generated by Django 3.0.2 on 2020-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0048_auto_20200416_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slots',
            name='free_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time_slots',
            name='total_seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
