# Generated by Django 3.0.2 on 2020-04-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0049_auto_20200416_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-id',), 'verbose_name': 'رویداد', 'verbose_name_plural': 'رویداد'},
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.IntegerField(blank=True, choices=[(1, 'بلیت فروشی آغاز نشده.'), (2, 'بلیت فروشی آغاز شده.'), (3, 'بلیت\u200cها تمام شد.'), (4, 'بلیت فروشی بسته شد.'), (5, 'رویداد به پایان رسیده'), (6, 'رویداد لغو شده'), (7, 'رویداد حذف شده')], null=True),
        ),
    ]
