# Generated by Django 3.0.2 on 2020-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0050_auto_20200418_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='تعداد نامحدود'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='تعداد نامحدود'),
        ),
    ]
