# Generated by Django 3.0.2 on 2020-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinfo', '0052_auto_20200421_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticket_reserved',
            field=models.IntegerField(default=0, verbose_name='بلیت\u200cهای رزرو'),
        ),
    ]
